apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ghost
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-storage
  claimRef:
    kind: PersistentVolumeClaim
    name: miblog
    namespace: ghost-blog
  nfs: 
    path: /exports-ocp4/ghost
    server: 192.168.50.254
