apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ghostbbdd
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-storage
  claimRef:
    kind: PersistentVolumeClaim
    name: miblog-database
    namespace: ghost-blog
  nfs: 
    path: /exports-ocp4/ghost-bbdd
    server: 192.168.50.254
